/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p3;

import javax.swing.JInternalFrame;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Andres
 */
public class Frame extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        ingredientNameLabel = new javax.swing.JLabel();
        ingredientTypeLabel = new javax.swing.JLabel();
        ingredientDescLabel = new javax.swing.JLabel();
        ingredientDescriptionField = new javax.swing.JTextField();
        ingredientTypeField = new javax.swing.JTextField();
        ingredientNameField = new javax.swing.JTextField();
        addIngredient = new javax.swing.JButton();
        deleteIngredient = new javax.swing.JButton();
        updateIngredient = new javax.swing.JButton();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        nutRecipeNameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nutritionNameField = new javax.swing.JTextField();
        nutritionCaloriesField = new javax.swing.JTextField();
        nutritionCaloriesFatField = new javax.swing.JTextField();
        nutritionTotalFatField = new javax.swing.JTextField();
        nutritionCholesterolField = new javax.swing.JTextField();
        nutritionSodiumField = new javax.swing.JTextField();
        nutritionTotalCarbField = new javax.swing.JTextField();
        nutritionProteinField = new javax.swing.JTextField();
        addNutrition = new javax.swing.JButton();
        deleteNutrition = new javax.swing.JButton();
        updateNutrition = new javax.swing.JButton();
        jInternalFrame5 = new javax.swing.JInternalFrame();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        recipeTypeField = new javax.swing.JTextField();
        recipeTimeField = new javax.swing.JTextField();
        recipeDescriptionField = new javax.swing.JTextField();
        addRecipe = new javax.swing.JButton();
        deleteRecipe = new javax.swing.JButton();
        updateRecipe = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Recipes");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Breakfast");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Omlett");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Chicken & Waffles");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("PB&B Smoothie");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Lunch");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Chicken Salad");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Cobb Salad");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Greek Pasta Salad");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Dinner");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Lasagna");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Baked Ziti");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Maple Salmon");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addTreeExpansionListener(new javax.swing.event.TreeExpansionListener() {
            public void treeCollapsed(javax.swing.event.TreeExpansionEvent evt) {
            }
            public void treeExpanded(javax.swing.event.TreeExpansionEvent evt) {
                jTree1TreeExpanded(evt);
            }
        });
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jTextField1.setText("Recipe");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jInternalFrame1.setVisible(true);
        jInternalFrame1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jInternalFrame1PropertyChange(evt);
            }
        });

        jLabel1.setText("Ingredients ");

        jButton2.setText("Instructions");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 252, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nutritional Facts"
            }
        ));
        jTable2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable2PropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jInternalFrame2.setVisible(true);
        jInternalFrame2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jInternalFrame2PropertyChange(evt);
            }
        });

        jLabel2.setText("Instructions");

        jButton3.setText("Nutrition ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 287, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextField3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3))
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton1)))
                .addGap(79, 79, 79)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jInternalFrame1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton1))
                    .addComponent(jInternalFrame2))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Recipes", jPanel3);

        jInternalFrame3.setTitle("Ingredient");
        jInternalFrame3.setVisible(true);

        ingredientNameLabel.setText("Name");

        ingredientTypeLabel.setText("Type");

        ingredientDescLabel.setText("Description");

        addIngredient.setText("Add Ingredient");

        deleteIngredient.setText("Delete Ingredient");

        updateIngredient.setText("Update Ingredient");

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ingredientDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ingredientTypeLabel)
                            .addComponent(ingredientNameLabel)
                            .addComponent(ingredientDescLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ingredientNameField)
                            .addComponent(ingredientTypeField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(addIngredient)
                        .addGap(32, 32, 32)
                        .addComponent(deleteIngredient))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(updateIngredient)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientNameLabel)
                    .addComponent(ingredientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientTypeLabel)
                    .addComponent(ingredientTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(ingredientDescLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingredientDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addIngredient)
                    .addComponent(deleteIngredient))
                .addGap(18, 18, 18)
                .addComponent(updateIngredient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jInternalFrame4.setTitle("Nutrition");
        jInternalFrame4.setVisible(true);

        nutRecipeNameLabel.setText("Recipe Name");

        jLabel3.setText("Calories");

        jLabel4.setText("Calories Fat");

        jLabel5.setText("Total Fat");

        jLabel6.setText("Cholesterol");

        jLabel7.setText("Sodium");

        jLabel8.setText("Total Carbohydrates");

        jLabel9.setText("Protein");

        addNutrition.setText("Add Nutrition");

        deleteNutrition.setText("Delete Nutrition");

        updateNutrition.setText("Update Nutrition");

        javax.swing.GroupLayout jInternalFrame4Layout = new javax.swing.GroupLayout(jInternalFrame4.getContentPane());
        jInternalFrame4.getContentPane().setLayout(jInternalFrame4Layout);
        jInternalFrame4Layout.setHorizontalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(nutRecipeNameLabel)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nutritionNameField)
                            .addComponent(nutritionCaloriesField)
                            .addComponent(nutritionCaloriesFatField)
                            .addComponent(nutritionTotalFatField)
                            .addComponent(nutritionCholesterolField)
                            .addComponent(nutritionSodiumField)
                            .addComponent(nutritionTotalCarbField)
                            .addComponent(nutritionProteinField, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)))
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(addNutrition)
                        .addGap(45, 45, 45)
                        .addComponent(deleteNutrition))
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(updateNutrition)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jInternalFrame4Layout.setVerticalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nutRecipeNameLabel)
                    .addComponent(nutritionNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nutritionCaloriesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nutritionCaloriesFatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nutritionTotalFatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nutritionCholesterolField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nutritionSodiumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nutritionTotalCarbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nutritionProteinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNutrition)
                    .addComponent(deleteNutrition))
                .addGap(18, 18, 18)
                .addComponent(updateNutrition)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jInternalFrame5.setTitle("Recipe");
        jInternalFrame5.setVisible(true);

        jLabel10.setText("Type");

        jLabel11.setText("Time");

        jLabel12.setText("Description");

        addRecipe.setText("Add Recipe");

        deleteRecipe.setText("Delete Recipe");

        updateRecipe.setText("Update Recipe");

        javax.swing.GroupLayout jInternalFrame5Layout = new javax.swing.GroupLayout(jInternalFrame5.getContentPane());
        jInternalFrame5.getContentPane().setLayout(jInternalFrame5Layout);
        jInternalFrame5Layout.setHorizontalGroup(
            jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame5Layout.createSequentialGroup()
                .addGroup(jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jInternalFrame5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(recipeDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame5Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addGroup(jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jInternalFrame5Layout.createSequentialGroup()
                                    .addGroup(jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel10))
                                    .addGap(42, 42, 42)
                                    .addGroup(jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(recipeTypeField)
                                        .addComponent(recipeTimeField, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))
                                .addGroup(jInternalFrame5Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel12)))))
                    .addGroup(jInternalFrame5Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(addRecipe)
                        .addGap(32, 32, 32)
                        .addComponent(deleteRecipe))
                    .addGroup(jInternalFrame5Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(updateRecipe)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jInternalFrame5Layout.setVerticalGroup(
            jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(recipeTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(recipeTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recipeDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRecipe)
                    .addComponent(deleteRecipe))
                .addGap(18, 18, 18)
                .addComponent(updateRecipe)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jInternalFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInternalFrame4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInternalFrame5)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jInternalFrame3)
                    .addComponent(jInternalFrame4)
                    .addComponent(jInternalFrame5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add New Recipe", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        // Will open an internal frame with Ingredients
        jInternalFrame1.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jInternalFrame2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jInternalFrame2PropertyChange
        // TODO add your handling code here:
        jInternalFrame2.setVisible(false);
    }//GEN-LAST:event_jInternalFrame2PropertyChange

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable2PropertyChange
     
        
    }//GEN-LAST:event_jTable2PropertyChange

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jInternalFrame1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jInternalFrame1PropertyChange
        // TODO add your handling code here:
        jInternalFrame1.setVisible(false);

    }//GEN-LAST:event_jInternalFrame1PropertyChange

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jInternalFrame2.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        // Display in text field node clicked
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree1.getSelectionPath().getLastPathComponent();
        jTextField1.setText(selectedNode.getUserObject().toString());
    }//GEN-LAST:event_jTree1MouseClicked

    private void jTree1TreeExpanded(javax.swing.event.TreeExpansionEvent evt) {//GEN-FIRST:event_jTree1TreeExpanded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTree1TreeExpanded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setSize(500, 500);
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addIngredient;
    private javax.swing.JButton addNutrition;
    private javax.swing.JButton addRecipe;
    private javax.swing.JButton deleteIngredient;
    private javax.swing.JButton deleteNutrition;
    private javax.swing.JButton deleteRecipe;
    private javax.swing.JLabel ingredientDescLabel;
    private javax.swing.JTextField ingredientDescriptionField;
    private javax.swing.JTextField ingredientNameField;
    private javax.swing.JLabel ingredientNameLabel;
    private javax.swing.JTextField ingredientTypeField;
    private javax.swing.JLabel ingredientTypeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JInternalFrame jInternalFrame5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel nutRecipeNameLabel;
    private javax.swing.JTextField nutritionCaloriesFatField;
    private javax.swing.JTextField nutritionCaloriesField;
    private javax.swing.JTextField nutritionCholesterolField;
    private javax.swing.JTextField nutritionNameField;
    private javax.swing.JTextField nutritionProteinField;
    private javax.swing.JTextField nutritionSodiumField;
    private javax.swing.JTextField nutritionTotalCarbField;
    private javax.swing.JTextField nutritionTotalFatField;
    private javax.swing.JTextField recipeDescriptionField;
    private javax.swing.JTextField recipeTimeField;
    private javax.swing.JTextField recipeTypeField;
    private javax.swing.JButton updateIngredient;
    private javax.swing.JButton updateNutrition;
    private javax.swing.JButton updateRecipe;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the addIngredient
     */
    public javax.swing.JButton getAddIngredient() {
        return addIngredient;
    }

    /**
     * @param addIngredient the addIngredient to set
     */
    public void setAddIngredient(javax.swing.JButton addIngredient) {
        this.addIngredient = addIngredient;
    }

    /**
     * @return the addNutrition
     */
    public javax.swing.JButton getAddNutrition() {
        return addNutrition;
    }

    /**
     * @param addNutrition the addNutrition to set
     */
    public void setAddNutrition(javax.swing.JButton addNutrition) {
        this.addNutrition = addNutrition;
    }

    /**
     * @return the addRecipe
     */
    public javax.swing.JButton getAddRecipe() {
        return addRecipe;
    }

    /**
     * @param addRecipe the addRecipe to set
     */
    public void setAddRecipe(javax.swing.JButton addRecipe) {
        this.addRecipe = addRecipe;
    }

    /**
     * @return the deleteIngredient
     */
    public javax.swing.JButton getDeleteIngredient() {
        return deleteIngredient;
    }

    /**
     * @param deleteIngredient the deleteIngredient to set
     */
    public void setDeleteIngredient(javax.swing.JButton deleteIngredient) {
        this.deleteIngredient = deleteIngredient;
    }

    /**
     * @return the deleteNutrition
     */
    public javax.swing.JButton getDeleteNutrition() {
        return deleteNutrition;
    }

    /**
     * @param deleteNutrition the deleteNutrition to set
     */
    public void setDeleteNutrition(javax.swing.JButton deleteNutrition) {
        this.deleteNutrition = deleteNutrition;
    }

    /**
     * @return the deleteRecipe
     */
    public javax.swing.JButton getDeleteRecipe() {
        return deleteRecipe;
    }

    /**
     * @param deleteRecipe the deleteRecipe to set
     */
    public void setDeleteRecipe(javax.swing.JButton deleteRecipe) {
        this.deleteRecipe = deleteRecipe;
    }

    /**
     * @return the ingredientDescriptionField
     */
    public javax.swing.JTextField getIngredientDescriptionField() {
        return ingredientDescriptionField;
    }

    /**
     * @param ingredientDescriptionField the ingredientDescriptionField to set
     */
    public void setIngredientDescriptionField(javax.swing.JTextField ingredientDescriptionField) {
        this.ingredientDescriptionField = ingredientDescriptionField;
    }

    /**
     * @return the ingredientNameField
     */
    public javax.swing.JTextField getIngredientNameField() {
        return ingredientNameField;
    }

    /**
     * @param ingredientNameField the ingredientNameField to set
     */
    public void setIngredientNameField(javax.swing.JTextField ingredientNameField) {
        this.ingredientNameField = ingredientNameField;
    }

    /**
     * @return the ingredientTypeField
     */
    public javax.swing.JTextField getIngredientTypeField() {
        return ingredientTypeField;
    }

    /**
     * @param ingredientTypeField the ingredientTypeField to set
     */
    public void setIngredientTypeField(javax.swing.JTextField ingredientTypeField) {
        this.ingredientTypeField = ingredientTypeField;
    }

    /**
     * @return the nutritionCaloriesFatField
     */
    public javax.swing.JTextField getNutritionCaloriesFatField() {
        return nutritionCaloriesFatField;
    }

    /**
     * @param nutritionCaloriesFatField the nutritionCaloriesFatField to set
     */
    public void setNutritionCaloriesFatField(javax.swing.JTextField nutritionCaloriesFatField) {
        this.nutritionCaloriesFatField = nutritionCaloriesFatField;
    }

    /**
     * @return the nutritionCaloriesField
     */
    public javax.swing.JTextField getNutritionCaloriesField() {
        return nutritionCaloriesField;
    }

    /**
     * @param nutritionCaloriesField the nutritionCaloriesField to set
     */
    public void setNutritionCaloriesField(javax.swing.JTextField nutritionCaloriesField) {
        this.nutritionCaloriesField = nutritionCaloriesField;
    }

    /**
     * @return the nutritionCholesterolField
     */
    public javax.swing.JTextField getNutritionCholesterolField() {
        return nutritionCholesterolField;
    }

    /**
     * @param nutritionCholesterolField the nutritionCholesterolField to set
     */
    public void setNutritionCholesterolField(javax.swing.JTextField nutritionCholesterolField) {
        this.nutritionCholesterolField = nutritionCholesterolField;
    }

    /**
     * @return the nutritionNameField
     */
    public javax.swing.JTextField getNutritionNameField() {
        return nutritionNameField;
    }

    /**
     * @param nutritionNameField the nutritionNameField to set
     */
    public void setNutritionNameField(javax.swing.JTextField nutritionNameField) {
        this.nutritionNameField = nutritionNameField;
    }

    /**
     * @return the nutritionProteinField
     */
    public javax.swing.JTextField getNutritionProteinField() {
        return nutritionProteinField;
    }

    /**
     * @param nutritionProteinField the nutritionProteinField to set
     */
    public void setNutritionProteinField(javax.swing.JTextField nutritionProteinField) {
        this.nutritionProteinField = nutritionProteinField;
    }

    /**
     * @return the nutritionSodiumField
     */
    public javax.swing.JTextField getNutritionSodiumField() {
        return nutritionSodiumField;
    }

    /**
     * @param nutritionSodiumField the nutritionSodiumField to set
     */
    public void setNutritionSodiumField(javax.swing.JTextField nutritionSodiumField) {
        this.nutritionSodiumField = nutritionSodiumField;
    }

    /**
     * @return the nutritionTotalCarbField
     */
    public javax.swing.JTextField getNutritionTotalCarbField() {
        return nutritionTotalCarbField;
    }

    /**
     * @param nutritionTotalCarbField the nutritionTotalCarbField to set
     */
    public void setNutritionTotalCarbField(javax.swing.JTextField nutritionTotalCarbField) {
        this.nutritionTotalCarbField = nutritionTotalCarbField;
    }

    /**
     * @return the nutritionTotalFatField
     */
    public javax.swing.JTextField getNutritionTotalFatField() {
        return nutritionTotalFatField;
    }

    /**
     * @param nutritionTotalFatField the nutritionTotalFatField to set
     */
    public void setNutritionTotalFatField(javax.swing.JTextField nutritionTotalFatField) {
        this.nutritionTotalFatField = nutritionTotalFatField;
    }

    /**
     * @return the recipeDescriptionField
     */
    public javax.swing.JTextField getRecipeDescriptionField() {
        return recipeDescriptionField;
    }

    /**
     * @param recipeDescriptionField the recipeDescriptionField to set
     */
    public void setRecipeDescriptionField(javax.swing.JTextField recipeDescriptionField) {
        this.recipeDescriptionField = recipeDescriptionField;
    }

    /**
     * @return the recipeTimeField
     */
    public javax.swing.JTextField getRecipeTimeField() {
        return recipeTimeField;
    }

    /**
     * @param recipeTimeField the recipeTimeField to set
     */
    public void setRecipeTimeField(javax.swing.JTextField recipeTimeField) {
        this.recipeTimeField = recipeTimeField;
    }

    /**
     * @return the recipeTypeField
     */
    public javax.swing.JTextField getRecipeTypeField() {
        return recipeTypeField;
    }

    /**
     * @param recipeTypeField the recipeTypeField to set
     */
    public void setRecipeTypeField(javax.swing.JTextField recipeTypeField) {
        this.recipeTypeField = recipeTypeField;
    }

    /**
     * @return the updateIngredient
     */
    public javax.swing.JButton getUpdateIngredient() {
        return updateIngredient;
    }

    /**
     * @param updateIngredient the updateIngredient to set
     */
    public void setUpdateIngredient(javax.swing.JButton updateIngredient) {
        this.updateIngredient = updateIngredient;
    }

    /**
     * @return the updateNutrition
     */
    public javax.swing.JButton getUpdateNutrition() {
        return updateNutrition;
    }

    /**
     * @param updateNutrition the updateNutrition to set
     */
    public void setUpdateNutrition(javax.swing.JButton updateNutrition) {
        this.updateNutrition = updateNutrition;
    }

    /**
     * @return the updateRecipe
     */
    public javax.swing.JButton getUpdateRecipe() {
        return updateRecipe;
    }

    /**
     * @param updateRecipe the updateRecipe to set
     */
    public void setUpdateRecipe(javax.swing.JButton updateRecipe) {
        this.updateRecipe = updateRecipe;
    }
}
